ipc_socket = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#808080"
blue = "#5c5cff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.cursor]
cursor = "#07fff2"

[colors.normal]
black = "#000000"
blue = "#4646ff"
cyan = "#00cdcd"
green = "#99ff33"
magenta = "#cd00cd"
red = "#cd0000"
white = "#e5e5e5"
yellow = "#cdcd00"

[colors.primary]
background = "#000000"

[font]
size = 11.0

[font.bold]
family = "monospace"

[font.bold_italic]
family = "monospace"

[font.italic]
family = "monospace"

[font.normal]
family = "monospace"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Last"
key = 5
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "First"
key = 7
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "D"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Alt"

[window]
opacity = 0.98
